module StatesHelper
  def us_states_str
    [
      ['Everything', ''],
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end

  def us_states_int
    [
          ['Everywhere', ''],
          ['Alabama', ],
          ['Alaska', 2],
          ['Arizona', 3],
          ['Arkansas', 4],
          ['California', 5],
          ['Colorado', 6],
          ['Connecticut', 7],
          ['Delaware', 8],
          ['Florida', 9],
          ['Georgia', 10,],
          ['Hawaii', 11],
          ['Idaho', 12],
          ['Illinois', 13],
          ['Indiana', 14],
          ['Iowa', 15],
          ['Kansas', 16],
          ['Kentucky', 17],
          ['Louisiana', 18],
          ['Maine', 19],
          ['Maryland', 20],
          ['Massachusetts', 21],
          ['Michigan', 22],
          ['Minnesota', 23],
          ['Mississippi', 24],
          ['Missouri', 25],
          ['Montana', 26],
          ['Nebraska', 27],
          ['Nevada', 28],
          ['New Hampshire', 29],
          ['New Jersey', 30],
          ['New Mexico', 31],
          ['New York', 32],
          ['North Carolina', 33],
          ['North Dakota', 34],
          ['Ohio', 35],
          ['Oklahoma', 36],
          ['Oregon', 37],
          ['Pennsylvania', 38],
          ['Rhode Island', 39],
          ['South Carolina', 40],
          ['South Dakota', 41],
          ['Tennessee', 42],
          ['Texas', 43],
          ['Utah', 44],
          ['Vermont', 45],
          ['Virginia', 46],
          ['Washington', 47],
          ['West Virginia', 48],
          ['Wisconsin', 49],
          ['Wyoming', 50],
          ['Washington DC', 51]
                              
        ]
  end
end
